### PR TITLE
Apply chameleon theme

### PR DESCRIPTION
**Pull request by guoyunhe**
I updated [Chameleon theme](https://github.com/openSUSE/opensuse-theme-chameleon) and try to apply the theme to doc.o.o . It's older version has been adopted to wikis and software.o.o. I will update all of them to latest version soon. So users can navigate between sites with smooth experience.

The theme support dark/light mode switch and localization support.

Changed to Google Custom Search (not work anymore) to DuckDuckGo search form. In this way, we don't need to load JavaScript from third party websites, which is better for user privacy.

Please scroll down to check the latest screenshots.

### CODE REVIEW

**Comment by hellcp** [comment]
I think the thing I like the most is the dark theme colouration, it's really great.

I can tell the inspiration behind this are the older Ubuntu double navbars ;)
Screenshot from 2019-07-29 10-01-05

Site specific actions, like language and darkmode selectors are in a project-wide navbar, which suggests that on every websiite listed in that navbar you will have the same language and darkmode if you select them, which is not true. Project-wide navbar should be a piece of code you can slap on every website and it will just work, which is just not true in this case.

Site-wide navbar includes links to documentation for specific pieces of software. In case you do this, everyone will want in on the fun. Every other software will want to be included at the top, because it makes it easier, which will at some point exceed the width of the bar.

How about something like:
Screenshot from 2019-07-29 10-27-26

Where the first navbar is openSUSE, the second one is site's. We could go as far as to get back to bento's roots and use categories for representing all the sites (because we will run out of space at some point otherwise)
Screenshot from 2019-07-29 10-43-46
Also, footer seems a little empty, it's a great place to let people know about everything we can't fit in the header ;)

**Comment by guoyunhe** [comment]
About the language dropdown and dark mode switch: in my plan I want them to be a global option and it can be supported in some way (though it is not working right now). For example, if you set a language in Google, then all Google sites, Google Drive, Google Maps, GMail, etc., will change to the language you chose. This will be a nice feature.



I considered the above suggestion but OBS, openQA, Weblate, already have a very thick navbar from Bootsrap:

image

image

image

For these sites, I am not sure if we can replace their navbar. If we cannot, then here will be two Bootstrap thick navbars. But with the little black bar, it is okay that we don't touch anything else, just adding the little black bar.

I have updated the cross site navbar to support all links that the footer used to have.

Screenshot_2019-07-29 openSUSE Documentation

This is also for compatibility. OBS site now has its own footer things:

image

All these changes aim one purpose: put all cross site content into a single small bar and leave the most page area to the site content itself.

The new site specific navbar is copied from KDE (they also use Bootstrap but in a stylish way) :laughing:

image

**Comment by hellcp** [comment]
I wouldn't worry as much about the colour of the navbar, project-wide one might as well be white ;) In case of OBS, I'm hoping it will be themable enough that we will be able to change that part about it. But that is so far into the future I doubt we will be able to have any openSUSE styling in OBS before the footer will no longer be there ;)

Having a global language switcher will be impossible more or less, every single service that we use has different ways to set a language. Google is at the liberty to have been the only developer on their own services ;)

Is the black a branding conscious idea? I don't think black is very openSUSE-like. I would go as far as to say, project-wide navbar should be the one that is green with logo and everything, not the site-wide navbar. And yes, I agree, it should be smaller than the site-wide navbar.

Dropdown also misses dropdown-item class everywhere ;)

Splitting the project-wide navbar into categories still seems like a better idea than a single long "more" list. It already has some categories, so that shouldn't be too hard.

KDE used the boostrap styling way better, especially since they didn't use abnormaly large font for the "KDE UserBase Wiki" as you did with "Documentation" and didn't use primary colour for every single navbar link ;)

**Comment by guoyunhe** [comment]
Dark mode option can be implemented with this https://github.com/zendesk/cross-storage#overview since it is backend independent.

Language selector can be different. For example, wiki has multiple sites for different languages. So I will move it to site specific navbar.

The black color is indeed a problem. I am looking for a dark enough color for those users who want to protect their eyes. But I cannot find a good one from openSUSE Branding Guidelines. The previous one is still too light for a dark background. And it is blueish. Do you have any ideas for the color of dark mode background and navbars?

**Comment by guoyunhe** [comment]
Updated site navbar. The site navbar is the same as Bootstrap navbar, just modified the brand background to green. Language selector was moved to site navbar.

image

**Comment by hellcp** [comment]
I have a wildly different proposal, I was hacking on software-o-o, to make the pages a little bit nicer:
Screenshot from 2019-09-16 22-34-03
While the logo there might be a little too small, chameleon with text openSUSE next to it should do the job just fine. I decided to get social media on the right, because the darkmode switch still doesn't do it for me there, it's a one time setting in a constant place, makes no particular sense. A light bar would integrate into the sites that don't require additional bar nicely, and it would split away from a dark second navbar pretty well. A set of menus scales better than having a contest to be featured in the navbar.

**Comment by guoyunhe** [comment]
I checked Google/Microsoft's design:

image

image

They have one thing in common: links of other sites are in a pop up menu of a 9-dot icon. Rest of part of the navbar is used for site function, like search, notifications.

For software.opensuse.org , maybe we can put the search box in navbar, which is the most used function of the site. Rest parts, like other sites and social media, can be minimized in a pop up menu.

In this way, we can keep a single navbar and compatibility with other apps, like Weblate (with a lot of items in navbar).

**Comment by hellcp** [comment]
You might wanna look into reimplementing [fedmenu](https://github.com/fedora-infra/fedmenu) for openSUSE, the concept is similar enough, it shows a list of websites for the Fedora infrastructure in a small popup.

**Comment by guoyunhe** [comment]
Yes, that is what I am thinking.

**Comment by guoyunhe** [comment]
@hellcp finally I got some time to finish this I called "Megamenu"

截图 2019-11-12 20 38 43-fullpage

Demo: https://opensuse.github.io/chameleon/

It is available through CDN https://static.opensuse.org/chameleon/ (probably need to wait for 30 minutes to update)

**Comment by hellcp** [comment]
I love it, although it's a little bit boring, no icons, no images? There are also some missing links, but I suppose that's the easiest to fix.

**Comment by hellcp** [comment]
I also wouldn't mind if the idea wasn't that fedora inspired, it would be nice if the modal was more of a dropdown, just so we don't kill the flow of the apps with just this widget

**Comment by guoyunhe** [comment]
Agree. The entire modal is made from JS. So it can be easily updated to whatever shape in future.

I also like to have some icons but don't have them in hand.

I see your PR #1 is based on Jekyll. That is probably a better way to go. The Jekyll theme can be reused for many static sites. KDE also has one https://invent.kde.org/websites/jekyll-kde-theme
In future if the navbar/footer thing change, we just need to update the jekyll theme package.

**Comment by hellcp** [comment]
We actually have multiple jekyll templates at this point:

- https://github.com/openSUSE/openSUSE-jekyll-news-theme
- https://github.com/openSUSE/news-o-o
- https://github.com/openSUSE/search-o-o

and probably more that I don't remember rn

**Comment by guoyunhe** [comment]
Is it possible to unify them into one theme?

**Comment by hellcp** [comment]
I'm thinking how we could utilize git submodules for that, considering how structure specific jekyll is.

One idea that comes to mind is having two git repos, which would be imported as submodules in `_includes` and `_layouts` respectively, so we can refer to them in jekyll as `layout: chameleon/default` and `{% include chameleon/nav.html %}` for example

**Comment by guoyunhe** [comment]
The best way is to use CDN. (KDE Jekyll theme does this way) The Jekyll theme link to full URL to https://static.opensuse.org/chameleon/dist/...

In this way, loading speed of these websites will be much faster because they cached the same CSS, JS and fonts. Also, if we change the theme style, the update will automatically apply to every site, without manually creating PR and waiting for months to be deployed.

**Comment by guoyunhe** [comment]
Template should be provided by the Jekyll theme, because it will contain markups specific to Jeykyll. Chameleon should only provides CSS, JS, fonts and icons. And here will be a single Jeykll theme providing these templates. Other sites just use the same Jekyll theme to get these templates. It is same amount of work for maintenance.

**Pull request closed without merging**
